### ISSUE TITLE
As DAVINCI PM I want a pipeline for the STODT application and publish it to stodt.davinci.bz.it

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/stodt#7] opened 2020-02-20 13:43 UTC
- [ ] Create a pipeline
- [ ] Deploy STODT application under stodt.davinci.bz.it

**Comment by Piiit** [comment] 2020-02-21 07:35
@LucaMiotto duplicate of #6

**Closed as completed by Piiit** 2020-02-21 07:35 UTC
